# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8524eb79c9be3b31109bd2d7ca454532f41ddf4a929811f93e8222529792fdd08a8b8677d203664d31fd5734babd6a457ac18d08ac630a887fbddfbd5dd3037

test:
  secret_key_base: a0a7302c4d7ed86f54495467e845a550367f1cb6cac4a8344af9416eebf421a684852a45df3a4e840c38afafdd983141c7a6e54b3a2dbfae29a9945864ab74cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
